### ISSUE TITLE
Can't access to webpage

### ISSUE THREAD

**Issue by VictorLzm** [ahmettekeli/AppleMusicToSpotify#1]
Hi,
I built the project with npm and got it running.
```
% npm start

> apple-music-to-spotify-frontend@1.0.0 start
> nodemon ./src/Server/server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./src/Server/server.js`
```
But it seems freezed or whatever and I can't reach it from any browser at `localhost:3000` or `127.0.0.1:3000`

Btw you should add a section in #readme.md with nodemon and express install commands 

[macOS Monterey]

**Comment by ahmettekeli** [comment]
Hi, 
It seems like you only started the server. There are commands to start the frontend in package.json. 
you should run both `npm run start` which starts the server and that runs on port 3004 and  `npm run start-dev` which starts the frontend and you should be able to view on localhost:3000. 
Make sure you have a valid **.env** file in the root folder with the related information.

Thanks for the suggestion i will make necessary changes on readme.md
